version: "3.3"

services:
  bgpmonitor-dump:
    build: ./bgpdownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
      - /etc/peering/monitor/config.json:/root/config.json
  ripemonitor-dump:
    build: ./ripedownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
      - /etc/peering/monitor/config.json:/root/config.json
  peeringrov-dataprocessing:
    build: ./dataprocessing
    volumes:
      - /etc/peering/monitor/data/:/var/monitor/data
      - /etc/peering/monitor/config.json:/root/config.json
