version: "3.3"

services:
  peeringrov-bgpmonitor:
    build: ./bgpdownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
    env_file:
      - /etc/peering/monitor/env
  peeringrov-ripemonitor:
    build: ./ripedownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
    env_file:
      - /etc/peering/monitor/env
  peeringrov-dataprocessing:
    build: ./dataprocessing
    volumes:
      - /etc/peering/monitor/data/:/var/monitor/data
