version: "3.3"

services:
  peeringrov-bgpmonitor:
    build: ./bgpmonitor
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
    env_file:
      - /etc/peering/monitor/env
  peeringrov-ripemonitor:
    build: ./ripemonitor
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
    env_file:
      - /etc/peering/monitor/env
